In [7]:
print("Hello")

Hello


Data Science

In [7]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(a ** b)

[ 5  7 15]
[ 4 10 54]
[     1     32 531441]


In [6]:
print(np.sqrt(a))
print(np.exp(a)) ## e = 2.718

1.4142135623730951
[ 2.71828183  7.3890561  20.08553692]


STATISTICAL AGGREGATION 

In [15]:
import numpy as np 
data1 = np.array([[1,2] ,[3,4]])
data2 = np.array([1,2,3])
print(np.sum(data1))
print(np.sum(data2))
print(np.mean(data1))
print(np.max(data1))
print(np.min(data1))

10
6
2.5
4
1


In [17]:
##use of axis 
data1 = np.array([[1,2] 
                  ,[3,4]])
data2 = np.array([1,2,3])
print(np.sum(data1 , axis=0))
print(np.sum(data1 , axis=1))
##axix = 0   column 
##axis = 1 row 

[4 6]
[3 7]


In [18]:
## RESHAPING 
## Covert the any dim array to any other dimenstionality 
flat = np.array([1,2,3,4,5,6])
matrix = flat.reshape(3,2)
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
##Boolean Masking 
arr = np.array([12,34,5,223,1])
mask = arr>20
print(mask)

[False  True False  True False]
